**Project FinSafe: Data-Driven Coastal Safety**

Imagine traveling to Florida for the ultimate surfing trip or a dream beach vacation, stepping onto the sand, and having zero idea that you are standing in a documented shark activity hotspot. Every year, millions of tourists and water-sports enthusiasts enter the water completely unaware of local risks. We are here to change that before they paddle out.

**The Solution: Proactive, Data-Backed Awareness**

Project FinSafe is a Florida-based NGO dedicated to closing the information gap between ocean goers and marine safety. Instead of generic warnings, we combine marine wildlife tracking with precise data analytics to protect lives, support tourism, and promote safe coexistence with ocean wildlife.

**How We Do It**


- **Data-First Targeting:** We analyze historical attack documentation and regional records to pinpoint the exact beaches and coastal zones with the highest incident frequencies.
- **Targeted Interventions:** We bypass vague warnings by deploying striking, highly visible safety signs right at those high-risk access points.
- **On-the-Ground Education:** We partner with local surf schools, dive shops, and beachside hotels to distribute practical awareness flyers directly to tourists and practitioners who need it most.


**To drive our mission with precision, these are four critical questions to be answered using historical data:**

1. Which country should we operate in?
2. Which is the most dangerous location for sea activities?
3. Which is the least dangerous location for sea activities?
4. Which shark specimens are responsible for the most attacks?
5. What is the exact percentage breakdown of fatal, non-fatal, and unknown outcomes?


By answering these questions with hard data rather than guesswork, we ensure our signs, flyers, and educational campaigns are deployed precisely where they can save the most lives.

In [21]:
import numpy as np
import pandas as pd

In [22]:
#Database run
df = pd.read_excel(r'C:\Users\franc\Desktop\Ironhack\Week_2\Project\GSAF5.xls', engine='xlrd')

In [23]:
#Duplicate drop - based on the full database
df = df.drop_duplicates()

In [25]:
#General Data cleaning for fluid workflow
df = df[["Country","State", "Location", "Fatal Y/N"]]

df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
    .str.replace("/", "_")
)

df["country"] = df["country"].fillna("N/A")

df["state"] = df["state"].fillna("N/A")

df["location"] = df["location"].fillna("N/A")

df["country"] = df["country"].str.strip().str.replace("'", "").str.upper()

df["state"] = df["state"].str.strip().str.replace("'", "").str.upper()

In [26]:
#Fatal Attacks Clean
unique_fatal = df["fatal_y_n"].unique()

df["fatal_y_n"] = df["fatal_y_n"].astype(str)
unique_fatal = df["fatal_y_n"].unique()

df["fatal_y_n"] = df["fatal_y_n"].str.strip().str.replace("'", "").str.upper()
unique_fatal = df["fatal_y_n"].unique()

fatal_mapping = {
    "Y": "Y",
    "N": "N",
    "M": "N",
    "NQ": "N",
    "F": "Unknown",
    "UNKNOWN": "Unknown",
    "2017": "Unknown",
    "Y X 2": "Unknown"
    
}

df["fatal_y_n"] = df["fatal_y_n"].replace(fatal_mapping)

df["fatal_y_n"] = df["fatal_y_n"].fillna("Unknown")

In [28]:
#Value counts to understand where the company should operate & Convert to a DataFrame
top_countries_df = df['country'].value_counts().head(3).reset_index()
top_countries_df.columns = ['country', 'attack_count']

top_countries_df

        country  attack_count
0           USA          2597
1     AUSTRALIA          1538
2  SOUTH AFRICA           599

In [30]:
#Value counts for state
top_state_df = df['state'].value_counts().head(3).reset_index()
top_state_df.columns = ['state', 'attack_count']

top_state_df

             state  attack_count
0          FLORIDA          1200
1  NEW SOUTH WALES           523
2              N/A           487

In [37]:
#Filtering the chosen country and location
filtered_df = df.loc[(df["country"] == "USA") & (df["state"] == "FLORIDA")]
filtered_df = filtered_df.reset_index(drop=True)
filtered_df

     country    state                                      location fatal_y_n
0        USA  FLORIDA                              New Smyrna Beach         N
1        USA  FLORIDA                        30 miles off Pensacola         N
2        USA  FLORIDA              Boca Grande (island in the keys)         N
3        USA  FLORIDA           Daytona Beach Shores Volusia County         N
4        USA  FLORIDA              Reservation Way near Indian Pass         N
...      ...      ...                                           ...       ...
1195     USA  FLORIDA                       Key West, Monroe County         N
1196     USA  FLORIDA              Riviera Beach, Palm Beach County         N
1197     USA  FLORIDA  Mosquito Inlet (Ponce Inlet), Volusia County         Y
1198     USA  FLORIDA                 Palm Beach, Palm Beach County         N
1199     USA  FLORIDA                      Gadsden Point, Tampa Bay         N

[1200 rows x 4 columns]

In [48]:
#Showing the value count  for each location and the total sum
display(filtered_df["location"].value_counts())
print(f"The total amount of attacks in Florida State is: {filtered_df['location'].value_counts().sum()}")

location
New Smyrna Beach, Volusia County                191
Daytona Beach, Volusia County                    31
Ponce Inlet, Volusia County                      28
Melbourne Beach, Brevard County                  20
Cocoa Beach, Brevard  County                     18
                                               ...
Cape Sable, Monroe County                         1
Near Fernandina Bar, Nassau County                1
Pensacola Harbor, Escambia County                 1
Lost Tree Village, Palm Beach County              1
Mosquito Inlet (Ponce Inlet), Volusia County      1
Name: count, Length: 568, dtype: int64

The total amount of attacks in Florida State is: 1200

In [80]:
# Top 5 dangerous places
loc_counts = filtered_df["location"].value_counts()
total_attacks = loc_counts.sum()
top_5 = loc_counts.head(5)

top_5_df = top_5.reset_index()
top_5_df.columns = ['Location', 'Count']

top_5_df.insert(0, 'Rank', range(1, len(top_5_df) + 1))

display(top_5_df)

   Rank                          Location  Count
0     1  New Smyrna Beach, Volusia County    191
1     2     Daytona Beach, Volusia County     31
2     3       Ponce Inlet, Volusia County     28
3     4   Melbourne Beach, Brevard County     20
4     5      Cocoa Beach, Brevard  County     18

In [53]:
#Top five dangerous locations - percentage wise
loc_counts = filtered_df["location"].value_counts()
total_attacks = loc_counts.sum()
top_5 = loc_counts.head(5)

print("The locations with the most shark attacks reported are:")

i = 1
for location, count in top_5.items():
    percentage = (count / total_attacks) * 100
    print(f"Top {i} = {location}: {percentage:.2f}%")
    i += 1

The locations with the most shark attacks reported are:
Top 1 = New Smyrna Beach, Volusia County: 15.92%
Top 2 = Daytona Beach, Volusia County: 2.58%
Top 3 = Ponce Inlet, Volusia County: 2.33%
Top 4 = Melbourne Beach, Brevard County: 1.67%
Top 5 = Cocoa Beach, Brevard  County: 1.50%

In [66]:
#Random safest locations from the lowest valu
loc_counts = filtered_df["location"].value_counts()
target_counts = [5, 4, 3, 2, 1]
random_list = []

for count in target_counts:
    matching_locs = loc_counts[loc_counts == count]
    

    if len(matching_locs) > 0:
        random_loc = matching_locs.sample(n=1)
        random_list.append(pd.DataFrame({'Location': random_loc.index, 'Count': random_loc.values}))

if random_list:
    random_table = pd.concat(random_list, ignore_index=True)
    display(random_table)
else:
    print("No matching locations found for those counts.")

                                          Location  Count
0                  Fernandina Beach, Nassau County      5
1                                Palm Beach County      4
2                  Vilano Beach, St.  Johns County      3
3                      Canaveral National Seashore      2
4  Sebastian Inlet, Indian River or Brevard County      1

In [69]:
# Top safest places - Percentage wise
random_dict = random_table.set_index('Location')['Count'].to_dict()

print("The locations with the lowest shark attacks reported are:")

i = 1
for location, count in reversed(random_dict.items()):
    percentage = (count / total_attacks) * 100
    print(f"Top {i} = {location}: {percentage:.2f}%")
    i += 1

The locations with the lowest shark attacks reported are:
Top 1 = Sebastian Inlet, Indian River or Brevard County: 0.08%
Top 2 = Canaveral National Seashore: 0.17%
Top 3 = Vilano Beach, St.  Johns County: 0.25%
Top 4 = Palm Beach County: 0.33%
Top 5 = Fernandina Beach, Nassau County: 0.42%

In [18]:
df.isna().sum()

country      0
state        0
location     0
fatal_y_n    0
dtype: int64

In [70]:
location_summary = df_1.pivot_table(
    index="location",
    columns="fatal_y_n",
    aggfunc="size"
)
display(location_summary)

fatal_y_n                                             N  Unknown   Y
location
 Cocoa Beach, Brevard  County                       1.0      NaN NaN
 Daytona Beach, Volusia County                      1.0      NaN NaN
 Marathon, Monroe County                            NaN      1.0 NaN
 New Smyrna Beach, Volusia County                   1.0      NaN NaN
 Palm Beach County                                  1.0      NaN NaN
...                                                 ...      ...  ..
Winterhaven Park,           Ponce Inlet, Volusi...  1.0      NaN NaN
World Typhoon Lagoon, Disney Water Park, Orange...  1.0      NaN NaN
a creek near Jacksonville, Duval County             1.0      NaN NaN
a pier at the end of Caxambas Drive, Marco Island   1.0      NaN NaN
½ mile offshore & 9 miles north of Fort Pierce      1.0      NaN NaN

[568 rows x 3 columns]

In [98]:
#Attack outcome - pivot table
location_summary = df_1.pivot_table(
    index="location",
    columns="fatal_y_n",
    aggfunc="size",
    fill_value=0
)

location_summary = location_summary.reindex(
    location_summary.sum(axis=1).sort_values(ascending=False).index
)

display(location_summary)

fatal_y_n                                             N  Unknown  Y
location
New Smyrna Beach, Volusia County                    188        3  0
Daytona Beach, Volusia County                        31        0  0
Ponce Inlet, Volusia County                          28        0  0
Melbourne Beach, Brevard County                      19        1  0
Cocoa Beach, Brevard  County                         17        1  0
...                                                 ...      ... ..
Winterhaven Park,           Ponce Inlet, Volusi...    1        0  0
World Typhoon Lagoon, Disney Water Park, Orange...    1        0  0
a creek near Jacksonville, Duval County               1        0  0
a pier at the end of Caxambas Drive, Marco Island     1        0  0
27th Avenue, New Smyrna Beach, Volusia County         1        0  0

[568 rows x 3 columns]

In [76]:
# Fatal/ Non-Fatal attacks percentage
fatal_counts = filtered_df['fatal_y_n'].value_counts()
total_attacks = len(filtered_df)

fatal_pct = (fatal_counts.get('Y', 0) / total_attacks) * 100
non_fatal_pct = (fatal_counts.get('N', 0) / total_attacks) * 100
unknown_pct = (fatal_counts.get('Unknown', 0) / total_attacks) * 100

# Print the requested text format
print(f"Percentage of fatal attacks: {fatal_pct:.2f}%")
print(f"Percentage of non-fatal attacks: {non_fatal_pct:.2f}%")
print(f"Percentage of attacks that the outcome is unknown: {unknown_pct:.2f}%")

Percentage of fatal attacks: 4.00%
Percentage of non-fatal attacks: 89.75%
Percentage of attacks that the outcome is unknown: 6.25%

In [93]:
#Dangerous - Fatal and non-fatal percentage
top_5_dangerous = filtered_df["location"].value_counts().head(5).index
df_dangerous = filtered_df[filtered_df["location"].isin(top_5_dangerous)]

pivot_dangerous = df_dangerous.pivot_table(
    index="location",
    columns="fatal_y_n",
    aggfunc="size",
    fill_value=0
)

pivot_dangerous = pivot_dangerous.reindex(columns=['N', 'Y', 'Unknown'], fill_value=0)

pivot_dangerous_pct = (pivot_dangerous.div(pivot_dangerous.sum(axis=1), axis=0) * 100).round(2)

print("Top 5 Dangerous Locations - Outcome Percentages:")
display(pivot_dangerous_pct)

Top 5 Dangerous Locations - Outcome Percentages:

fatal_y_n                              N    Y  Unknown
location
Cocoa Beach, Brevard  County       94.44  0.0     5.56
Daytona Beach, Volusia County     100.00  0.0     0.00
Melbourne Beach, Brevard County    95.00  0.0     5.00
New Smyrna Beach, Volusia County   98.43  0.0     1.57
Ponce Inlet, Volusia County       100.00  0.0     0.00

In [94]:
#Safe - Fatal and non-fatal percentage
top_5_safest = filtered_df["location"].value_counts().sort_values(ascending=True).head(5).index
df_safest = filtered_df[filtered_df["location"].isin(top_5_safest)]

pivot_safest = df_safest.pivot_table(
    index="location",
    columns="fatal_y_n",
    aggfunc="size",
    fill_value=0
)

# Force the columns to always include N, Y, and UNKNOWN (filling missing ones with 0)
pivot_safest = pivot_safest.reindex(columns=['N', 'Y', 'Unknown'], fill_value=0)

pivot_safest_pct = (pivot_safest.div(pivot_safest.sum(axis=1), axis=0) * 100).round(2)

print("Top 5 Safest Locations - Outcome Percentages:")
display(pivot_safest_pct)

Top 5 Safest Locations - Outcome Percentages:

fatal_y_n                                      N    Y  Unknown
location
 Riviera Beach, Palm Beach County          100.0  0.0      0.0
Haulover Inlet, Dade County                100.0  0.0      0.0
North Dade- Interama area of Biscayne Bay  100.0  0.0      0.0
Stuart Beach, Martin County                100.0  0.0      0.0
West Palm Beach, Palm Beach County         100.0  0.0      0.0

In [97]:
#Filtered file creation
filtered_df.to_csv('shark_attacks_filtered.csv', sep=";", encoding="utf-8", index=False)